version: '3'
services:
  frontend:
    build: ./console
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend  
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7 
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: book_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    restart: always
volumes:
  db-data:
